export const EVENT_METADATA = 'CQRS_EVENT_METADATA';
export const EVENTS_HANDLER_METADATA = 'CQRS_EVENTS_HANDLER_METADATA';
export const COMMAND_METADATA = 'CQRS_COMMAND_METADATA';
export const COMMAND_HANDLER_METADATA = 'CQRS_COMMAND_HANDLER_METADATA';
export const QUERY_METADATA = 'CQRS_QUERY_METADATA';
export const QUERY_HANDLER_METADATA = 'CQRS_QUERY_HANDLER_METADATA';
export const SAGA_METADATA = 'CQRS_SAGA_METADATA';

export const EVENT_HANDLER_INSTANCES = 'CQRS_EVENT_HANDLER_INSTANCES';
export const COMMAND_HANDLER_INSTANCES = 'CQRS_COMMAND_HANDLER_INSTANCES';
export const QUERY_HANDLER_INSTANCES = 'CQRS_QUERY_HANDLER_INSTANCES';
export const SAGA_CLASS_INSTANCES = 'CQRS_SAGA_CLASS_INSTANCES';
export const SAGA_FUNCTIONS = 'CQRS_SAGA_FUNCTIONS';
export const SAGA_FACTORIES_INLINE = 'CQRS_SAGA_FACTORIES_INLINE';
