name: Analyze Lockfile Workflow

on:
  pull_request:
    branches: [master, development]
    paths-ignore:
      - 'docs/**'
      - '**.mdx?'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  analyze-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Analyze Lockfile Dependencies
        uses: ./.github/actions/security/lockfile
        with:
          path: 'yarn.lock'
          type: 'yarn'
          allowedHosts: 'registry.npmjs.org registry.yarnpkg.com github.com codeload.github.com'
          allowedURLs: 'https://github.com/bitpay/node-buffers.git#commit=fb509ded0d7f1fc0f6fa6662abf9e533018a57df https://codeload.github.com/bitpay/node-buffers/tar.gz/fb509ded0d7f1fc0f6fa6662abf9e533018a57df'

